### ISSUE TITLE
新版手机qq不方便带字发图了

### ISSUE THREAD

**Issue by lolikyo** [watermellye/arena#14]
能不能改成先发指令再发图

**Comment by watermellye** [comment]
你好！
最晚在端午期间实装此修改。
另，现在手机QQ可以通过[长按聊天文字输入框->右侧三点->全屏输入]的方式插入图片。

**Comment by lolikyo** [comment]
> 你好！
> 最晚在端午期间实装此修改。
> 另，现在手机QQ可以通过[长按聊天文字输入框->右侧三点->全屏输入]的方式插入图片。

好的，小米魔改了长按输入框的功能，覆盖了应用自带选项，一直没发现这个功能。只能输入到第四行时候触发全屏输入按钮出现并点击进入。另外手机QQ发送出去带图文字，但是插件好像拿不到图片并报错了。PS:使用电脑QQ和TIM是可以拿到图片并识别的。

**Comment by watermellye** [comment]
根据bot使用的前端（通信端）不一样，可能出现各种问题。有的可以通过修改代码临时解决（例如：将`&amp;`转为&；删除spec及之后的字段）；有的缺少了token，需要手动拼一段token上去，或者等待通信端更新。

如果您仍未解决此问题，可以在这里附上报错信息

**Comment by lolikyo** [comment]
> 根据bot使用的前端（通信端）不一样，可能出现各种问题。有的可以通过修改代码临时解决（例如：将`&amp;`转为&；删除spec及之后的字段）；有的缺少了token，需要手动拼一段token上去，或者等待通信端更新。
> 
> 如果您仍未解决此问题，可以在这里附上报错信息

https://github.com/Mrs4s/go-cqhttp/issues/2507 嗯，是gocqhttp的问题，可能也不会维护了

**Comment by watermellye** [comment]
https://github.com/watermellye/arena/commit/ec4ccb893a1ed5c2210d841a16d836d565887049
@666dechaoge

**Comment by lolikyo** [comment]
无论群里发送什么，都在报这个错误，是on_message的问题吗
[2024-06-11 10:32:29,674 pcr-arena] ERROR: wrapper() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
TypeError: wrapper() takes 1 positional argument but 2 were given

**Comment by lolikyo** [comment]
去掉了一个
```python
@sv.on_message('private')
```
之后不报错了，能用了，谢谢大佬

**Comment by watermellye** [comment]
明白了。是我修改了hoshino的wrapper。默认不能这么写。
你把on_group和on_private拆开就行。
或者你不需要私聊的话，on_private去掉即可。
我稍后上传修复。

**Comment by lolikyo** [comment]
指令前缀和图片分开发送时候，出现了不影响使用的报错
```
[2024-06-11 10:58:11,316 pcr-arena] ERROR: <class 'nonebot.message.CanceledException'> occured when QueryArenaMessageContextInterface handling message -2147483197.
[2024-06-11 10:58:11,316 pcr-arena] ERROR: ServiceFunc of HoshinoBot finished.
Traceback (most recent call last):
  File "/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "/HoshinoBot/hoshino/modules/priconne/arena/__init__.py", line 88, in QueryArenaMessageContextInterface
    await QueryArenaImageAsync(image_url, req.region, bot, ev)
  File "/HoshinoBot/hoshino/modules/priconne/arena/__init__.py", line 92, in QueryArenaImageAsync
    await _QueryArenaImageAsync(image_url, Region2Int(region), bot, ev)
  File "/HoshinoBot/hoshino/modules/priconne/arena/old_main.py", line 484, in _QueryArenaImageAsync
    await generateCollisionFreeTeam(bot, ev, all_query_records, team_has_result, region, boxDict)  # 最多允许补两队
  File "/HoshinoBot/hoshino/modules/priconne/arena/old_main.py", line 659, in generateCollisionFreeTeam
    await bot.finish(ev, str(MessageSegment.image(pic2b64(teams))))
  File "/HoshinoBot/hoshino/__init__.py", line 30, in finish
    raise CanceledException('ServiceFunc of HoshinoBot finished.')
nonebot.message.CanceledException: ServiceFunc of HoshinoBot finished.
```
其中message -2147483197 是发指令之后发送的阵容截图

**Comment by watermellye** [comment]
这就是bot.finish的工作原理。通过抛出一个Exception来结束逻辑。
由于可能会导致外部代码出现意想不到的退出，并且由于该异常同样可被捕获，我在新写的代码里已经不再使用bot.finish。
