### ISSUE TITLE
无法识别mac版QQ传过来的图片

### ISSUE THREAD

**Issue by dgkkjt** [watermellye/arena#9]
[2023-04-11 14:10:56,252 pcr-arena] ERROR: cannot identify image file <_io.BytesIO object at 0x7f741b64fb80>
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/priconne/arena/__init__.py", line 76, in arena_query_b
    await _arena_query(bot, ev, region=2)
  File "/root/HoshinoBot/hoshino/modules/priconne/arena/__init__.py", line 498, in _arena_query
    image = Image.open(BytesIO(await get_pic(ret.group(2))))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f741b64fb80>

**Comment by watermellye** [comment]
不懂mac
